name: 'Build c4z'
description: 'Builds a c4z from a c4zproj in specified directory'
inputs:
  projectDir:
    description: 'Directory of project that contains the .c4zproj'
    required: true
  c4zproj:
    description: 'Name of c4zproj manifest file'
    required: true
  outputDir:
    description: 'Directory to output c4z file, relative to projectDir'
    required: true
    default: './../'
  version:
    description: 'Version to which the driver will be updated.'
    required: false
  updateModified:
    description: 'Should the driver modified date XML field be updated.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.projectDir }}
    - ${{ inputs.c4zproj }}
    - ${{ inputs.outputDir }}
    - ${{ inputs.version }}
    - ${{ inputs.updateModified }}
